### ISSUE TITLE
Text in paranthesis become interpreted

### ISSUE THREAD

**Issue by tsainez** [jeffreytse/jekyll-spaceship#3]
When no LaTeX is present in a post, anything in paranthesis is fine, but otherwise, it seems to remove all spaces and italicize the contents, as though it were being interpreted as LaTeX.

<img width="257" alt="Screen Shot 2020-05-13 at 3 54 50 AM" src="https://user-images.githubusercontent.com/13399044/81804187-93f90b00-94cd-11ea-9879-11b33bca9cf7.png">
<img width="374" alt="Screen Shot 2020-05-13 at 3 55 15 AM" src="https://user-images.githubusercontent.com/13399044/81804191-952a3800-94cd-11ea-8c08-563aff927442.png">

Can anyone else replicate this bug, or is solely on my end?

**Comment by jeffreytse** [comment]
Hi @tsainez

Since the `mathjax-processor` will add the mathjax script to html head with the default config automatically. Once the math engine was added,  the math engine that between "(" and ")" will be treated as math mode, so anything in paranthesis become interpreted.

Directly escape "()" in the HTML by using `<span class='tex2jax_ignore'>`, this will allow you to even escape "$".

For convenience,  the simplest workaround is to delete ['\\(','\\)'] of the default config in script, I will fix this issue as soon as possible.

**Comment by Tzeny** [comment]
I am also having this problem, where should I delete ['\(','\)'] from? I've tried searching my whole project for it and I came up empty handed.

**Comment by jeffreytse** [comment]
Hi @tsainez 

Now this issue was fixed and the latest release [v0.4.3](https://rubygems.org/gems/jekyll-spaceship) was published.
You can add this plugin for more awesome features in future.
